networks:
  kittycatsuperfun:
    external: false

services:
  # database for user/club data
  PRO290UserClubServiceDBSqlServer:
    container_name: PRO290UserClubServiceDBSqlServer
    image: mcr.microsoft.com/mssql/server:2019-latest    
    restart: always
    hostname: PRO290UserClubServiceDBSqlServer
    ports:
      - "1433:1433"
    volumes:
      - sqlservervolume:/var/opt/mssql
    networks:
      - kittycatsuperfun
    environment:
      SA_PASSWORD: "abc12345!"
      ACCEPT_EULA: "Y"

  PRO290UserServiceAPI:
    container_name: PRO290UserServiceAPI
    build:
      context: ./UserService
      dockerfile: Dockerfile
    image: pro290userserviceapi:1
    restart: always
    hostname: PRO290UserServiceAPI
    ports:
      - "8085:8080"
    networks:
      - kittycatsuperfun
  
  PRO290ClubServiceAPI:
    container_name: PRO290ClubServiceAPI
    build:
      context: ./ClubService
      dockerfile: Dockerfile
    image: pro290clubserviceapi:1
    restart: always
    hostname: PRO290ClubServiceAPI
    ports:
      - "8081:8080"
    networks:
      - kittycatsuperfun

  SEN300EurekaRegistry:
    container_name: SEN300EurekaRegistry
    image: steeltoeoss/eureka-server:latest
    restart: always
    hostname: SEN300EurekaRegistry
    ports:
      - 8761:8761
    networks:
      - kittycatsuperfun 

volumes:
  sqlservervolume: